/* @flow */
import { noop, extend } from 'shared/util';
import { warn as baseWarn, tip } from 'core/util/debug';
import { generateCodeFrame } from './codeframe';

type CompiledFunctionResult = {
  render: Function;
  staticRenderFns: Array<Function>;
};
function createFunction(code, errors) {
  try {
    return new Function(code);
  } catch (err) {
    errors.push({ err, code });
    return noop;
  }
}
export function createCompileToFunctionFn(compile: Function): Function {
  const cache = Object.create(null);
  return function compileToFunctions(
    template: string,
    options?: CompilerOptions,
    vm?: Component,
  ): CompiledFunctionResult {
    options = extend({}, options);
    const warn = options.warn || baseWarn;
    delete options.warn;
    // check cache
    const key = options.delimiters
      ? String(options.delimiters) + template
      : template;
    if (cache[key]) {
      return cache[key];
    }
    // compile
    const compiled = compile(template, options);
    // turn code into functions
    const res = {};
    const fnGenErrors = [];
    res.render = createFunction(compiled.render, fnGenErrors);
    res.staticRenderFns = compiled.staticRenderFns.map(code => {
      return createFunction(code, fnGenErrors);
    });
    // check function generation errors.
    // this should only happen if there is a bug in the compiler itself.
    // mostly for codegen development use
   return (cache[key] = res);
  };
}
